name: HTMLMinTests
on:
  push:
    branches: [ "compat-fixes" ]
  pull_request:
    branches: [ "compat-fixes" ]
jobs:
  htmlmin:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4', '8.0', '8.1', '8.2', '8.3']
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup PHP with Composer and extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-${{ matrix.php-versions }}-
    - name: Install Composer dependencies
      env:
        PHP_VERSION: ${{ matrix.php-versions }}
      run: composer install --no-progress --prefer-dist --optimize-autoloader
    - name: Run tests with code coverage
      env:
        PHP_VERSION: ${{ matrix.php-versions }}
      run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml
      continue-on-error: true
